### ISSUE TITLE
evebox with Elasticsearch database

### ISSUE THREAD

**Issue by rickygm** [jasonish/evebox#318] opened 2024-11-23 20:46 UTC
Hi, I'm using the latest version of Evebox and Elasticsearch. It started recording Suricata data, but then it gives me this error:

`evebox[1125]:` 2024-11-23 14:15:36 ERROR evebox::eve::processor: Failed to commit events (will try again): elasticsearch commit error: {"errors":true,"too

`uid":"GHbgCGeVSRaMkIjdIv6RaQ","shard":"0","index":"logstash-2024.11.23"}}},{"create":{"_index":"logstash-2024.11.23","_id":"01JDDA1Y5SN9S4HT5M4848FDJT","status"
:409,"error":{"type":"version_conflict_engine_exception","reason":"[01JDDA1Y5SN9S4HT5M4848FDJT]: version conflict, document already exists (current version [1])
","index_uuid":"GHbgCGeVSRaMkIjdIv6RaQ","shard":"0","index":"logstash-2024.11.23"}}},{"create":{"_index":"logstash-2024.11.23","_id":"01JDDA1Y5SDJ6ETKFX4RCV05KB
","status":409,"error":{"type":"version_conflict_engine_exception","reason":"[01JDDA1Y5SDJ6ETKFX4RCV05KB]: version conflict, document already exists (current ve
rsion [1])","index_uuid":"GHbgCGeVSRaMkIjdIv6RaQ","shard":"0","index":"logstash-2024.11.23"}}},{"create":{"_index":"logstash-2024.11.23","_id":"01JDDA1Y5SK4TJR2
96B78W73HV","status":409,"error":{"type":"version_conflict_engine_exception","reason":"[01JDDA1Y5SK4TJR296B78W73HV]: version conflict, document already exists (
current version [1])","index_uuid":"GHbgCGeVSRaMkIjdIv6RaQ","shard":"0","index":"logstash-2024.11.23"}}},{"create":{"_index":"logstash-2024.11.23","_id":"01JDDA
1Y5SQK0JQ5JQ8JSJJENK","status":409,"error":{"type":"version_conflict_engine_exception","reason":"[01JDDA1Y5SQK0JQ5JQ8JSJJENK]: version conflict, document alread
y exists (current version [1])","index_uuid":"GHbgCGeVSRaMkIjdIv6RaQ","shard":"0","index":"logstash-2024.11.23"}}},{"create":{"_index":"logstash-2024.11.23","_i
d":"01JDDA1Y5STVPH1H37H4211C5X","status":409,"error":{"type":"version_conflict_engine_exception","reason":"[01JDDA1Y5STVPH1H37H4211C5X]: version conflict, docum
ent already exists (current version [1])","index_uuid":"GHbgCGeVSRaMkIjdIv6RaQ","shard":"0","index":"logstash-2024.11.23"}}},{"create":{"_index":"logstash-2024.
11.23","_id":"01JDDA1Y5TESJVNAYM20GDJDTM","status":409,"error":{"type":"version_conflict_engine_exception","reason":"[01JDDA1Y5TESJVNAYM20GDJDTM]: version confl
ict, document already exists (current version [1])","index_uuid":"GHbgCGeVSRaMkIjdIv6RaQ","shard":"0","index":"logstash-2024.11.23"}}},{"create":{"_index":"logs
tash-2024.11.23","_id":"01JDDA1Y7PQMYTBR7X6XVP4Q1P","status":409,"error":{"type":"version_conflict_engine_exception","reason":"[01JDDA1Y7PQMYTBR7X6XVP4Q1P]: ver
sion conflict, document already exists (current version [1])","index_uuid":"GHbgCGeVSRaMkIjdIv6RaQ","shard":"0","index":"logstash-2024.11.23"}}}]}`

EveBox 0.18.2
elasticsearch  8.16.1
ubuntu 22.04
suricata 7.0.7

any help is apreciated

**Comment by jasonish** [comment] 2024-11-25 22:54
Restarting the EveBox process that is writing to Elasticsearch should fix this, until it happens again. I believe we enter this state when some, but not all of the records in a batch submission fail to add, we then retry the whole batch, but some made it in.

Solutions for code are:
- detect which ones were successful, which failed, only retry failed records
- in crease a version number to force overwrite

This is something I'll have to look into.

**Comment by rickygm** [comment] 2024-11-26 02:28
I restarted evebox several times, but without success, it always shows the same error and evebox does not show data in the web interface.

A question, how could I increase the number of versions to force writing?

regards!

**Comment by rickygm** [comment] 2024-11-26 02:30
I think this is it : `evebox elastic set-field-limit 5000`

**Comment by jasonish** [comment] 2024-11-26 16:11
> I think this is it : `evebox elastic set-field-limit 5000`

Typically when you run into this the error from Elastic is pretty clear that this is what needs to be done. I could however see this error happening, then being the cause of the error you posted above, so it could clear it up as well.

**Comment by rickygm** [comment] 2024-11-27 01:27
thank for your answer , but it doesn't accept the increase.

evebox elastic set-field-limit 5000
error: unexpected argument '5000' found

Usage: evebox elastic set-field-limit [OPTIONS]

For more information, try '--help'.

**Comment by jasonish** [comment] 2024-11-27 03:53
```
evebox elastic set-field-limit --limit 5000
```
add `-h` for the other options if you need to authenticate, or provide a custom URL.

**Comment by jasonish** [comment] 2024-11-27 03:54
Since the default of 1000 is never enough anymore, I'm probably going to make this automatic. I think that's the last item before a new release.

**Comment by rickygm** [comment] 2024-11-27 23:59
> ```
> evebox elastic set-field-limit --limit 5000
> ```
> 
> add `-h` for the other options if you need to authenticate, or provide a custom URL.

I try this way, but it doesn't allow me the command

evebox elastic set-field-limit --limit 5000 -e https://192.168.0.20:9200

`2024-11-27 17:57:24 ERROR evebox: error: invalid type: map, expected a sequence at line 1 column 0`

**Comment by rickygm** [comment] 2024-11-28 00:01
> Since the default of 1000 is never enough anymore, I'm probably going to make this automatic. I think that's the last item before a new release.

I think it would be better to add it in future versions, what I don't understand is why in this latest version this error is presented, in a version prior to elasticsearch it is running without problems

**Comment by jasonish** [comment] 2024-11-28 01:51
> `2024-11-27 17:57:24 ERROR evebox: error: invalid type: map, expected a sequence at line 1 column 0`

Bad error for what is likely an authentication error.  Use the `-u` and `-p` parameters to add the Elasticsearch username and password.  I just upgraded to Elasticsearch 8.16.1 and it works fine.

**Comment by jasonish** [comment] 2024-11-28 01:51
> I think it would be better to add it in future versions, what I don't understand is why in this latest version this error is presented, in a version prior to elasticsearch it is running without problems

Perhaps some new network activity. EveBox can work for sometime without issue, then Suricata generates some events with some new data that explodes the fields past the limit.

**Comment by rickygm** [comment] 2024-11-29 02:49
> > `2024-11-27 17:57:24 ERROR evebox: error: invalid type: map, expected a sequence at line 1 column 0`
> 
> Bad error for what is likely an authentication error. Use the `-u` and `-p` parameters to add the Elasticsearch username and password. I just upgraded to Elasticsearch 8.16.1 and it works fine.

It seems to be working now

👍

**Comment by rickygm** [comment] 2024-11-29 02:56
> > I think it would be better to add it in future versions, what I don't understand is why in this latest version this error is presented, in a version prior to elasticsearch it is running without problems
> 
> Perhaps some new network activity. EveBox can work for sometime without issue, then Suricata generates some events with some new data that explodes the fields past the limit.

I have a question here, if you are using elasticsearch as the main DB, why don't you leave a date range in evebox?

thank for you help.

**Comment by jasonish** [comment] 2024-11-29 04:17
> I have a question here, if you are using elasticsearch as the main DB, why don't you leave a date range in evebox?

I'm not quite sure what you mean, there is somewhat of a date range selector where it matters.  Its purely relative though, from now back a period of time.  I don't have a full spec date selector, at least not yet.

**Comment by jasonish** [comment] 2024-12-04 00:48
> That's what I was talking about, a specific date selector, I hope you can add it to future versions.

Yes,  soon.  Not being able to narrow in on a specific time frame is become annoying for me. I have to tag a new release soon for compatibility reasons of Elastic and  SQLite, then I think a date selector will likely become priority.

> 
> Thank you for your help, I made a small donation 👍

Thanks! Much appreciated!

**Comment by jasonish** [comment] 2024-12-13 18:26
Looks like this issue is resolved? Closing.  Please feel free to open another issue or discussion if not.

**Closed by jasonish** 2024-12-13 18:26 UTC
Labels: support

**Comment by rickygm** [comment] 2024-12-13 18:41
> Looks like this issue is resolved? Closing. Please feel free to open another issue or discussion if not.

yes, Problem solved, waiting for the new version 👍
