### ISSUE TITLE
wrong / old  DNS records read from suricata DNS logs  

### ISSUE THREAD

**Issue by StefanSa** [jasonish/evebox#11] opened 2015-05-08 14:19 UTC
Hi,
thank you for your nice tool evebox.
But it is not the best solution, the DNS Records from Suricata (DNS type) to read.
Here there are often old, false or expired DNS data and thereby
displays this incorrect DNS records in evebox which can be quite confusing to.

**Comment by jasonish** [comment] 2015-05-08 17:51
This is somewhat by design.

When resolving the hostnames, it looks for DNS events that happened at the same time or before the event, to get the hostname at the time of the event.

Maybe the idea here is flawed, and I should return the most current information, if a case can be made that that would be better.

I'll need to think about it.

**Comment by jasonish** [comment] 2016-07-06 06:55
DNS info has been removed.  It will need to be re-added and re-thought.

**Closed by jasonish** 2016-07-06 06:55 UTC
